In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dados = pd.read_csv(r'C:\Users\guilh\OneDrive\Documentos\GitHub\Enem-2021\DADOS\MICRODADOS_ENEM_2021.csv',sep=';',encoding='cp1252')

In [3]:
dados.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,210053865474,2021,5,F,1,1,1,1,3,1,...,A,A,A,B,A,A,B,A,B,B
1,210052384164,2021,12,M,1,1,1,1,11,1,...,A,A,A,B,A,A,C,A,A,A
2,210052589243,2021,13,F,3,1,1,1,15,1,...,B,A,A,B,A,A,C,B,B,B
3,210052128335,2021,3,M,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,B,B
4,210051353021,2021,2,F,1,3,1,2,0,2,...,B,A,A,B,A,B,E,A,B,B

In [4]:
dados.columns

Index(['NU_INSCRICAO', 'NU_ANO', 'TP_FAIXA_ETARIA', 'TP_SEXO',
       'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_NACIONALIDADE', 'TP_ST_CONCLUSAO',
       'TP_ANO_CONCLUIU', 'TP_ESCOLA', 'TP_ENSINO', 'IN_TREINEIRO',
       'CO_MUNICIPIO_ESC', 'NO_MUNICIPIO_ESC', 'CO_UF_ESC', 'SG_UF_ESC',
       'TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC',
       'CO_MUNICIPIO_PROVA', 'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA',
       'SG_UF_PROVA', 'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC',
       'TP_PRESENCA_MT', 'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC',
       'CO_PROVA_MT', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT',
       'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH', 'TX_RESPOSTAS_LC',
       'TX_RESPOSTAS_MT', 'TP_LINGUA', 'TX_GABARITO_CN', 'TX_GABARITO_CH',
       'TX_GABARITO_LC', 'TX_GABARITO_MT', 'TP_STATUS_REDACAO',
       'NU_NOTA_COMP1', 'NU_NOTA_COMP2', 'NU_NOTA_COMP3', 'NU_NOTA_COMP4',
       'NU_NOTA_COMP5', 'NU_NOTA_REDACAO', 'Q001', 'Q002', 'Q003', 'Q004',
       'Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013',
       'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022',
       'Q023', 'Q024', 'Q025'],
      dtype='object')

In [5]:
dados_usados = dados[['NU_INSCRICAO','TP_FAIXA_ETARIA', 'TP_SEXO',
       'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_NACIONALIDADE', 'TP_ST_CONCLUSAO',
       'TP_ANO_CONCLUIU', 'TP_ESCOLA', 'TP_ENSINO', 'IN_TREINEIRO','CO_MUNICIPIO_ESC', 'NO_MUNICIPIO_ESC', 'CO_UF_ESC', 'SG_UF_ESC',
       'TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC','TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC',
       'TP_PRESENCA_MT','NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT','TP_STATUS_REDACAO',
       'NU_NOTA_COMP1', 'NU_NOTA_COMP2', 'NU_NOTA_COMP3', 'NU_NOTA_COMP4',
       'NU_NOTA_COMP5', 'NU_NOTA_REDACAO','Q001', 'Q002','Q005', 'Q006','Q008','Q024', 'Q025']]

In [6]:
dados_usados_validos = dados_usados
dados_usados_invalidos = dados_usados

In [7]:
nulos = dados_usados.isnull().sum()
nulos = nulos[nulos[nulos.index]>0]
nulos

TP_ENSINO                 2293004
CO_MUNICIPIO_ESC          2576026
NO_MUNICIPIO_ESC          2576026
CO_UF_ESC                 2576026
SG_UF_ESC                 2576026
TP_DEPENDENCIA_ADM_ESC    2576026
TP_LOCALIZACAO_ESC        2576026
NU_NOTA_CN                1143988
NU_NOTA_CH                1011453
NU_NOTA_LC                1011453
NU_NOTA_MT                1143988
TP_STATUS_REDACAO         1011453
NU_NOTA_COMP1             1011453
NU_NOTA_COMP2             1011453
NU_NOTA_COMP3             1011453
NU_NOTA_COMP4             1011453
NU_NOTA_COMP5             1011453
NU_NOTA_REDACAO           1011453
Q001                            2
Q002                            2
Q005                            2
Q006                            2
Q008                            2
Q024                            2
Q025                            2
dtype: int64

In [8]:
na_tot = (nulos['TP_ENSINO']*100)/dados_usados.size

1,73% dos dados nÃ£o possuem informaÃ§Ãµes geogrÃ¡ficas. Dessa forma, para nÃ£o perder esse volume de informaÃ§Ãµes, serÃ¡ adicionado a categoria "Desconhecido". Para as informaÃ§Ãµes referentes a notas, serÃ¡ classificado como "ausente". Para informaÃ§Ãµes do questionÃ¡rio socioeconomico, serÃ£o classificados como "Nao informado".

In [9]:
dados_usados_validos[['TP_ENSINO']] = dados_usados[['TP_ENSINO']].fillna('Desconhecido')
dados_usados_validos[['CO_MUNICIPIO_ESC']] = dados_usados[['CO_MUNICIPIO_ESC']].fillna('Desconhecido')
dados_usados_validos[['NO_MUNICIPIO_ESC']] = dados_usados[['NO_MUNICIPIO_ESC']].fillna('Desconhecido')
dados_usados_validos[['CO_UF_ESC']] = dados_usados[['CO_UF_ESC']].fillna('Desconhecido')
dados_usados_validos[['SG_UF_ESC']] = dados_usados[['SG_UF_ESC']].fillna('Desconhecido')
dados_usados_validos[['TP_DEPENDENCIA_ADM_ESC']] = dados_usados[['TP_DEPENDENCIA_ADM_ESC']].fillna('Desconhecido')
dados_usados_validos[['TP_LOCALIZACAO_ESC']] = dados_usados[['TP_LOCALIZACAO_ESC']].fillna('Desconhecido')

C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\1957823351.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos[['TP_ENSINO']] = dados_usados[['TP_ENSINO']].fillna('Desconhecido')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\1957823351.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos[['CO_MUNICIPIO_ESC']] = dados_usados[['CO_MUNICIPIO_ESC']].fillna('Desconhecido')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\1957823351.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos[['NO_MUNICIPIO_ESC']] = dados_usados[['NO_MUNICIPIO_ESC']].fillna('Desconhecido')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\1957823351.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos[['CO_UF_ESC']] = dados_usados[['CO_UF_ESC']].fillna('Desconhecido')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\1957823351.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos[['SG_UF_ESC']] = dados_usados[['SG_UF_ESC']].fillna('Desconhecido')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\1957823351.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos[['TP_DEPENDENCIA_ADM_ESC']] = dados_usados[['TP_DEPENDENCIA_ADM_ESC']].fillna('Desconhecido')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\1957823351.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos[['TP_LOCALIZACAO_ESC']] = dados_usados[['TP_LOCALIZACAO_ESC']].fillna('Desconhecido')

In [10]:
dados_usados_validos['Q001'] = dados_usados['Q001'].fillna('Nao Informado')
dados_usados_validos['Q002'] = dados_usados['Q002'].fillna('Nao Informado')
dados_usados_validos['Q005'] = dados_usados['Q005'].fillna('Nao Informado')
dados_usados_validos['Q006'] = dados_usados['Q006'].fillna('Nao Informado')
dados_usados_validos['Q008'] = dados_usados['Q008'].fillna('Nao Informado')
dados_usados_validos['Q024'] = dados_usados['Q024'].fillna('Nao Informado')
dados_usados_validos['Q025'] = dados_usados['Q025'].fillna('Nao Informado')

C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\2693405545.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos['Q001'] = dados_usados['Q001'].fillna('Nao Informado')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\2693405545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos['Q002'] = dados_usados['Q002'].fillna('Nao Informado')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\2693405545.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos['Q005'] = dados_usados['Q005'].fillna('Nao Informado')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\2693405545.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos['Q006'] = dados_usados['Q006'].fillna('Nao Informado')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\2693405545.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos['Q008'] = dados_usados['Q008'].fillna('Nao Informado')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\2693405545.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos['Q024'] = dados_usados['Q024'].fillna('Nao Informado')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\2693405545.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos['Q025'] = dados_usados['Q025'].fillna('Nao Informado')

In [11]:
dados_usados_validos = dados_usados.dropna(0,how= 'any', inplace= False)

C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\2183795079.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  dados_usados_validos = dados_usados.dropna(0,how= 'any', inplace= False)

In [12]:
dados_usados_validos.head()

,NU_INSCRICAO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,...,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q005,Q006,Q008,Q024,Q025
1,210052384164,12,M,1,1,1,1,11,1,Desconhecido,...,120.0,80.0,560.0,B,B,3.0,B,B,A,A
3,210052128335,3,M,1,3,1,2,0,2,1.0,...,200.0,160.0,780.0,B,B,6.0,B,B,B,B
4,210051353021,2,F,1,3,1,2,0,2,1.0,...,180.0,180.0,780.0,D,E,4.0,C,B,B,B
8,210053417016,8,F,1,3,1,2,0,2,Desconhecido,...,100.0,100.0,520.0,B,B,2.0,B,B,A,B
9,210051128744,4,F,1,3,1,2,0,2,1.0,...,80.0,20.0,380.0,D,D,2.0,B,B,A,B

In [13]:
dados_usados_invalidos['NU_NOTA_CN'] = dados_usados['NU_NOTA_CN'].fillna('Ausente')
dados_usados_invalidos['NU_NOTA_CH'] = dados_usados['NU_NOTA_CH'].fillna('Ausente')
dados_usados_invalidos['NU_NOTA_LC'] = dados_usados['NU_NOTA_LC'].fillna('Ausente')
dados_usados_invalidos['NU_NOTA_MT'] = dados_usados['NU_NOTA_MT'].fillna('Ausente')
dados_usados_invalidos['TP_STATUS_REDACAO'] = dados_usados['TP_STATUS_REDACAO'].fillna('Ausente')
dados_usados_invalidos['NU_NOTA_COMP1'] = dados_usados['NU_NOTA_COMP1'].fillna('Ausente')
dados_usados_invalidos['NU_NOTA_COMP2'] = dados_usados['NU_NOTA_COMP2'].fillna('Ausente')
dados_usados_invalidos['NU_NOTA_COMP3'] = dados_usados['NU_NOTA_COMP3'].fillna('Ausente')
dados_usados_invalidos['NU_NOTA_COMP4'] = dados_usados['NU_NOTA_COMP4'].fillna('Ausente')
dados_usados_invalidos['NU_NOTA_COMP5'] = dados_usados['NU_NOTA_COMP5'].fillna('Ausente')
dados_usados_invalidos['NU_NOTA_REDACAO'] = dados_usados['NU_NOTA_REDACAO'].fillna('Ausente')

C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\4087160735.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_invalidos['NU_NOTA_CN'] = dados_usados['NU_NOTA_CN'].fillna('Ausente')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\4087160735.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_invalidos['NU_NOTA_CH'] = dados_usados['NU_NOTA_CH'].fillna('Ausente')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\4087160735.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_invalidos['NU_NOTA_LC'] = dados_usados['NU_NOTA_LC'].fillna('Ausente')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\4087160735.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_invalidos['NU_NOTA_MT'] = dados_usados['NU_NOTA_MT'].fillna('Ausente')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\4087160735.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_invalidos['TP_STATUS_REDACAO'] = dados_usados['TP_STATUS_REDACAO'].fillna('Ausente')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\4087160735.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_invalidos['NU_NOTA_COMP1'] = dados_usados['NU_NOTA_COMP1'].fillna('Ausente')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\4087160735.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_invalidos['NU_NOTA_COMP2'] = dados_usados['NU_NOTA_COMP2'].fillna('Ausente')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\4087160735.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_invalidos['NU_NOTA_COMP3'] = dados_usados['NU_NOTA_COMP3'].fillna('Ausente')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\4087160735.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_invalidos['NU_NOTA_COMP4'] = dados_usados['NU_NOTA_COMP4'].fillna('Ausente')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\4087160735.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_invalidos['NU_NOTA_COMP5'] = dados_usados['NU_NOTA_COMP5'].fillna('Ausente')
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\4087160735.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_invalidos['NU_NOTA_REDACAO'] = dados_usados['NU_NOTA_REDACAO'].fillna('Ausente')

In [14]:
dados_invalidos = dados_usados_invalidos[dados_usados_invalidos['NU_NOTA_CN']=='Ausente']
dados_invalidos = dados_invalidos[dados_invalidos['NU_NOTA_CH'] == 'Ausente']
dados_invalidos = dados_invalidos[dados_invalidos['NU_NOTA_LC'] == 'Ausente']
dados_invalidos = dados_invalidos[dados_invalidos['NU_NOTA_MT'] == 'Ausente']
dados_invalidos = dados_invalidos[dados_invalidos['TP_STATUS_REDACAO'] == 'Ausente']
dados_invalidos = dados_invalidos[dados_invalidos['NU_NOTA_COMP1'] == 'Ausente']
dados_invalidos = dados_invalidos[dados_invalidos['NU_NOTA_COMP2'] == 'Ausente']
dados_invalidos = dados_invalidos[dados_invalidos['NU_NOTA_COMP3'] == 'Ausente']
dados_invalidos = dados_invalidos[dados_invalidos['NU_NOTA_COMP4'] == 'Ausente']
dados_invalidos = dados_invalidos[dados_invalidos['NU_NOTA_COMP5'] == 'Ausente']
dados_invalidos = dados_invalidos[dados_invalidos['NU_NOTA_REDACAO'] == 'Ausente']

In [15]:
dados_invalidos

,NU_INSCRICAO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,...,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q005,Q006,Q008,Q024,Q025
2,210052589243,13,F,3,1,1,1,15,1,Desconhecido,...,Ausente,Ausente,Ausente,B,C,3.0,C,B,B,B
5,210052391248,10,F,1,3,1,1,9,1,Desconhecido,...,Ausente,Ausente,Ausente,H,E,1.0,B,B,A,B
7,210054368957,4,F,1,1,1,1,1,1,Desconhecido,...,Ausente,Ausente,Ausente,E,G,4.0,G,C,B,B
13,210051549956,5,M,1,2,1,1,3,1,Desconhecido,...,Ausente,Ausente,Ausente,B,E,4.0,D,B,A,B
14,210054173438,5,F,1,2,1,2,0,2,1.0,...,Ausente,Ausente,Ausente,G,E,1.0,B,B,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3389826,210052408816,9,F,1,2,1,1,6,1,Desconhecido,...,Ausente,Ausente,Ausente,B,D,3.0,C,B,A,B
3389827,210053249138,7,F,1,3,1,1,0,1,Desconhecido,...,Ausente,Ausente,Ausente,B,B,5.0,C,B,A,B
3389828,210053776013,7,F,1,1,1,1,5,1,Desconhecido,...,Ausente,Ausente,Ausente,E,E,4.0,G,C,B,B
3389829,210052441508,13,F,1,3,1,1,15,1,Desconhecido,...,Ausente,Ausente,Ausente,B,C,1.0,F,B,B,B
3389831,210052410399,12,F,2,3,1,1,15,1,Desconhecido,...,Ausente,Ausente,Ausente,Nao Informado,Nao Informado,Nao Informado,Nao Informado,Nao Informado,Nao Informado,Nao Informado

In [16]:
dados_usados_validos.reset_index(inplace=True)

SeparaÃ§Ã£o dos dados em tabelas

In [17]:
resumo_descricao = []
for i in range(0,len(dados_usados_validos['NU_INSCRICAO'])):
    resumo_descricao.append( str(dados_usados_validos['TP_FAIXA_ETARIA'][i]) + str(dados_usados_validos['TP_SEXO'][i]) + str(dados_usados_validos['TP_ESTADO_CIVIL'][i]) + str(dados_usados_validos['TP_COR_RACA'][i]) + str(dados_usados_validos['TP_NACIONALIDADE'][i]) + str(dados_usados_validos['TP_ST_CONCLUSAO'][i]) + str(dados_usados_validos['TP_ANO_CONCLUIU'][i])  + str(dados_usados_validos['TP_ESCOLA'][i]) + str(dados_usados_validos['TP_ENSINO'][i]))

In [18]:
dados_usados_validos['RESUMO_DESCRIACAO'] = resumo_descricao

C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\4105293527.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos['RESUMO_DESCRIACAO'] = resumo_descricao

In [19]:
resumo_questionario = []
for i in range(0,len(dados_usados_validos['NU_INSCRICAO'])):
    resumo_questionario.append( str(dados_usados_validos['Q001'][i]) + str(dados_usados_validos['Q002'][i]) + str(dados_usados_validos['Q005'][i]) + str(dados_usados_validos['Q006'][i]) + str(dados_usados_validos['Q008'][i]) + str(dados_usados_validos['Q024'][i]) + str(dados_usados_validos['Q025'][i]))

In [20]:
dados_usados_validos['RESUMO_QUESTIONARIO'] = resumo_questionario

C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\1428538091.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos['RESUMO_QUESTIONARIO'] = resumo_questionario

In [21]:
dicionario_escola = {
    'TP_DEPENDENCIA_ADM_ESC':{1.0:'Federal',2.0:'Estadual',3.0:'Municipal',4.0:'Privada'},
    'TP_LOCALIZACAO_ESC':{1.0:'Urbana',2.0:'Rural'},
    'TP_ENSINO':{1.0:'Ensino Regular',2.0:'Ensino Especial'},
    'TP_FAIXA_ETARIA':{1:'<17 anos',2:'17 anos', 3: '18 anos',4:'19 anos',5:'20 anos',6:'21 anos',7:'22 anos',8:'23 anos',9: '24 anos',10:'25 anos',11:'26 - 30 anos',12:'31 - 35 anos',13:'36 - 40 anos',14:'41 - 45 anos',15:'46 - 50 anos',16:'51-55 anos',17:'56-60 anos',18:'61-65 anos',19:'66-70 anos',20:'>20 anos'},
    'TP_SEXO':{'M':'Masculino','F':'Feminino'},
    'TP_ESTADO_CIVIL':{0:'NÃ£o declarado',1:'Solteiro(a)',2:'Casado',3:'Divorciado',4:'Viuvo(a)'},
    'TP_COR_RACA':{0:'NÃ£o declarado',1:'Branca',2:'Preta',3:'Parda',4:'Amarela',5:'IndÃ­gena',6:'NÃ£o sabe'},
    'TP_NACIONALIDADE':{0:'NÃ£o informado',1:'Brasileiro(a)',2:'Brasileiro(a) Naturalizado(a)',3:'Estrangeiro(a)',4:'Brasileiro(a) Nato(a)'},
    'TP_ST_CONCLUSAO':{0:'ConcluÃ­do',1:'Em 2021',2:'ApÃ³s 2021',3:'NÃ£o estuda'},
    'TP_ANO_CONCLUIU':{0:'NÃ£o Informado',1:'2020',2:'2019',3:'2018',4:'2017',5:'2016',6:'2015',7:'2014',8:'2013',9:'2012',10:'2011',11:'2010',12:'2009',13:'2008',14:'2007',15:'<2007'},
    'TP_ESCOLA':{1:'NÃ£o respondeu',2:'PÃºblica',3:'Privada'},
    'TP_PRESENCA_CN':{0:'Faltou',1:'Presente',2:'Eliminado'},
    'TP_PRESENCA_CH':{0:'Faltou',1:'Presente',2:'Eliminado'},
    'TP_PRESENCA_LC':{0:'Faltou',1:'Presente',2:'Eliminado'},
    'TP_PRESENCA_MT':{0:'Faltou',1:'Presente',2:'Eliminado'},
    'TP_STATUS_REDACAO':{1:'Normal',2:'Anulada',3:'CÃ³pia Texto Motivador',4:'Em Branco',6:'Fuga ao Tema',7:'Tipo Textual Incorreto',8:'Texto Insuficiente',9:'Parte desconectada'},
    'Q001':{'A':'Nunca estudou','B':'4/5 ano fundamental incompleto','C':'8/9 ano fundamental incompleto','D':'Ensino MÃ©dio Incompleto','E':'GraduaÃ§Ã£o Incompleta','F':'PÃ³s-GraduaÃ§Ã£o Incompleta','G':'PÃ³s-GraduaÃ§Ã£o Completa','H':'NÃ£o sei'},
    'Q002':{'A':'Nunca estudou','B':'4/5 ano fundamental incompleto','C':'8/9 ano fundamental incompleto','D':'Ensino MÃ©dio Incompleto','E':'GraduaÃ§Ã£o Incompleta','F':'PÃ³s-GraduaÃ§Ã£o Incompleta','G':'PÃ³s-GraduaÃ§Ã£o Completa','H':'NÃ£o sei'},
    'Q006':{'A':'Sem Renda','B':'AtÃ© 1100,00','C':'1100,01 atÃ© 1650,0','D':'1650,01 atÃ© 2200,00','E':'2200,01 atÃ© 2750,00','F':'2750,01 atÃ© 3300,00','G':'3300,01 atÃ© 4400,00','H':'4400,01 atÃ© 5500,00','I':'5500,01 atÃ© 6600,00','J':'6600,01 atÃ© 7700,00','K':'7700,01 atÃ© 8800,00','L':'8800,01 atÃ© 9900,00','M': '9900,01 atÃ© 11000,00','N':'11000,01 atÃ© 13200,00','O':'13200,01 atÃ© 16500,00','P':'16500,01 atÃ© 22000,00','Q':'Acima de 22000,00'},
    'Q008':{'A':'NÃ£o','B':'Um','C':'Dois','D':'TrÃªs','E':'Quatro'},
    'Q024':{'A':'NÃ£o','B':'Um','C':'Dois','D':'TrÃªs','E':'Quatro'},
    'Q025':{'A':'NÃ£o','B':'Sim'}
    
}

In [22]:
dados_invalidos.replace(dicionario_escola,inplace=True)
dados_usados_validos.replace(dicionario_escola,inplace=True)

C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\3942756892.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos.replace(dicionario_escola,inplace=True)

In [23]:
states = {
    'AC':'Acre',
    'AL':'Alagoas',
    'AP':'Amapa',
    'AM':'Amazonas',
    'BA':'Bahia',
    'CE':'Ceara',
    'DF':'Distrito Federal',
    'ES':'Espirito Santo',
    'GO':'Goias',
    'MA':'Maranhao',
    'MT':'Mato Grosso',
    'MS':'Mato Grosso do Sul',
    'MG':'Minas Gerais',
    'PA':'Para',
    'PB':'Paraiba',
    'PR':'Parana',
    'PE':'Pernambuco',
    'PI':'Piaui',
    'RJ':'Rio de Janeiro',
    'RN':'Rio Grande do Norte',
    'RS':'Rio Grande do Sul',
    'RO':'Rondonia',
    'RR':'Roraima',
    'SC':'Santa Catarina',
    'SP':'Sao Paulo',
    'SE':'Sergipe',
    'TO':'Tocantins'
}

In [24]:
regioes = {
    'Acre':'Norte',
    'Alagoas':'Nordeste',
    'Amapa':'Norte',
    'Amazonas':'Norte',
    'Bahia':'Nordeste',
    'Ceara':'Nordeste',
    'Distrito Federal':'Centro Oeste',
    'Espirito Santo':'Sudeste',
    'Goias':'Centro Oeste',
    'Maranhao':'Nordeste',
    'Mato Grosso':'Centro Oeste',
    'Mato Grosso do Sul':'Centro Oeste',
    'Minas Gerais':'Sudeste',
    'Para':'Norte',
    'Paraiba':'Nordeste',
    'Parana':'Sul',
    'Pernambuco':'Nordeste',
    'Piaui':'Nordeste',
    'Rio de Janeiro':'Sudeste',
    'Rio Grande do Norte':'Nordeste',
    'Rio Grande do Sul':'Sul',
    'Rondonia':'Norte',
    'Roraima':'Norte',
    'Santa Catarina':'Sul',
    'Sao Paulo':'Sudeste',
    'Sergipe':'Nordeste',
    'Tocantins':'Norte'
}

In [25]:
dados_usados_validos.replace({'SG_UF_ESC':states},inplace=True)
dados_usados_validos['Regiao'] = dados_usados_validos['SG_UF_ESC']
dados_usados_validos.replace({'Regiao':regioes},inplace=True)

C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\2516829372.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos.replace({'SG_UF_ESC':states},inplace=True)
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\2516829372.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos['Regiao'] = dados_usados_validos['SG_UF_ESC']
C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\2516829372.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos.replace({'Regiao':regioes},inplace=True)

In [26]:
dados_aluno = dados_usados_validos[['NU_INSCRICAO','NO_MUNICIPIO_ESC',
       'TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC','TP_NACIONALIDADE','RESUMO_QUESTIONARIO','RESUMO_DESCRIACAO']]

In [27]:
dados_localizacao = dados_usados_validos[['NO_MUNICIPIO_ESC','SG_UF_ESC','Regiao']]

In [28]:
dados_participante = dados_usados_validos[['RESUMO_DESCRIACAO','TP_FAIXA_ETARIA', 'TP_SEXO',
       'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_NACIONALIDADE', 'TP_ST_CONCLUSAO',
       'TP_ANO_CONCLUIU', 'TP_ESCOLA', 'TP_ENSINO']]

In [29]:
dados_prova = dados_usados_validos[['NU_INSCRICAO','TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC',
       'TP_PRESENCA_MT','NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT']]

In [30]:
dados_redacao = dados_usados_validos[['NU_INSCRICAO','TP_STATUS_REDACAO',
       'NU_NOTA_COMP1', 'NU_NOTA_COMP2', 'NU_NOTA_COMP3', 'NU_NOTA_COMP4',
       'NU_NOTA_COMP5', 'NU_NOTA_REDACAO']]

In [31]:
dados_socioeconomicos = dados_usados_validos[['RESUMO_QUESTIONARIO','Q001', 'Q002','Q005', 'Q006','Q008','Q024', 'Q025']]

In [32]:
dados_socioeconomicos = dados_socioeconomicos.drop_duplicates()
dados_localizacao = dados_localizacao.drop_duplicates('NO_MUNICIPIO_ESC')
dados_participante = dados_participante.drop_duplicates('RESUMO_DESCRIACAO')

In [33]:
print(len(dados_localizacao['NO_MUNICIPIO_ESC'].unique()))
print(len(dados_localizacao))
print(len(dados_socioeconomicos['RESUMO_QUESTIONARIO'].unique()))

5216
5216
77222

Exportando os dados

In [34]:
dados_socioeconomicos.to_csv("Dim_socioeconomica.csv")

In [35]:
dados_participante.to_csv("Dim_caracteristicas.csv")

In [36]:
dados_aluno.to_csv("Dim_Aluno.csv")

In [37]:
dados_localizacao.to_csv("Dim_Loc.csv")

In [38]:
dados_prova.to_csv("Dim_Prova.csv")

In [39]:
dados_redacao.to_csv("Dim_Redacao.csv")

In [40]:

q001 = dados_usados_validos[['NO_MUNICIPIO_ESC','Q001']].groupby(['NO_MUNICIPIO_ESC','Q001']).value_counts().reset_index()
q002 = dados_usados_validos[['NO_MUNICIPIO_ESC','Q002']].groupby(['NO_MUNICIPIO_ESC','Q002']).value_counts().reset_index()
q005 = dados_usados_validos[['NO_MUNICIPIO_ESC','Q005']].groupby(['NO_MUNICIPIO_ESC','Q005']).value_counts().reset_index()
q006 = dados_usados_validos[['NO_MUNICIPIO_ESC','Q006']].groupby(['NO_MUNICIPIO_ESC','Q006']).value_counts().reset_index()
q008 = dados_usados_validos[['NO_MUNICIPIO_ESC','Q008']].groupby(['NO_MUNICIPIO_ESC','Q008']).value_counts().reset_index()
q024 = dados_usados_validos[['NO_MUNICIPIO_ESC','Q024']].groupby(['NO_MUNICIPIO_ESC','Q024']).value_counts().reset_index()
q025 = dados_usados_validos[['NO_MUNICIPIO_ESC','Q025']].groupby(['NO_MUNICIPIO_ESC','Q025']).value_counts().reset_index()

In [41]:
q001.rename(columns={0:'Quantidade'},inplace=True)
q002.rename(columns={0:'Quantidade'},inplace=True)
q005.rename(columns={0:'Quantidade'},inplace=True)
q006.rename(columns={0:'Quantidade'},inplace=True)
q008.rename(columns={0:'Quantidade'},inplace=True)
q024.rename(columns={0:'Quantidade'},inplace=True)
q025.rename(columns={0:'Quantidade'},inplace=True)

In [42]:
q001.to_csv('q001.csv')
q002.to_csv('q002.csv')
q005.to_csv('q005.csv')
q006.to_csv('q006.csv')
q008.to_csv('q008.csv')
q024.to_csv('q024.csv')
q025.to_csv('q025.csv')

In [43]:
dados_prova['NU_NOTA_CH'].mean()

523.1820297242268

In [44]:
dados_prova['soma'] = (dados_prova['NU_NOTA_CH'] + dados_prova['NU_NOTA_CN'] + dados_prova['NU_NOTA_LC'] + dados_prova['NU_NOTA_MT'])/4

C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\3020228305.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_prova['soma'] = (dados_prova['NU_NOTA_CH'] + dados_prova['NU_NOTA_CN'] + dados_prova['NU_NOTA_LC'] + dados_prova['NU_NOTA_MT'])/4

In [45]:
dados_usados_validos['soma'] = (dados_usados_validos['NU_NOTA_CH'] + dados_usados_validos['NU_NOTA_CN'] + dados_usados_validos['NU_NOTA_LC'] + dados_usados_validos['NU_NOTA_MT'])/4

C:\Users\guilh\AppData\Local\Temp\ipykernel_21532\1284869899.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_usados_validos['soma'] = (dados_usados_validos['NU_NOTA_CH'] + dados_usados_validos['NU_NOTA_CN'] + dados_usados_validos['NU_NOTA_LC'] + dados_usados_validos['NU_NOTA_MT'])/4

In [46]:
dados_usados_validos[['soma','SG_UF_ESC']].groupby('SG_UF_ESC').mean()

                           soma
SG_UF_ESC
Acre                 489.837617
Alagoas              501.247114
Amapa                482.590683
Amazonas             466.887460
Bahia                503.506581
Ceara                480.841033
Desconhecido         512.899369
Distrito Federal     529.597725
Espirito Santo       523.984947
Goias                505.576376
Maranhao             482.658220
Mato Grosso          505.621674
Mato Grosso do Sul   509.272754
Minas Gerais         540.510978
Para                 488.318012
Paraiba              504.161204
Parana               526.620395
Pernambuco           504.718706
Piaui                501.477061
Rio Grande do Norte  521.440192
Rio Grande do Sul    531.318164
Rio de Janeiro       533.222798
Rondonia             490.831839
Roraima              495.801438
Santa Catarina       533.750092
Sao Paulo            539.831360
Sergipe              507.163705
Tocantins            486.884468

In [48]:
len(dados_usados_validos[dados_usados_validos['NO_MUNICIPIO_ESC'] == 'RibeirÃ£o Pires'])

394